// Copyright (c) Sci.NET Foundation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Sci.NET.CUDA.RuntimeApi.Bindings.Exceptions;

/// <summary>
/// This indicates that the provided PTX was compiled with an unsupported toolchain. The most common reason for this, is the PTX was generated by a compiler newer than what is supported by the CUDA driver and PTX JIT compiler.
/// </summary>
[PublicAPI]
public class CudaUnsupportedPtxVersionException : CudaException
{
    private const string DefaultMessage =
        "This indicates that the provided PTX was compiled with an unsupported toolchain. The most common reason for this, is the PTX was generated by a compiler newer than what is supported by the CUDA driver and PTX JIT compiler.";

    /// <summary>
    /// Initializes a new instance of the <see cref="CudaUnsupportedPtxVersionException"/> class.
    /// </summary>
    /// <remarks>
    /// This indicates that the provided PTX was compiled with an unsupported toolchain. The most common reason for this, is the PTX was generated by a compiler newer than what is supported by the CUDA driver and PTX JIT compiler.
    /// </remarks>
    public CudaUnsupportedPtxVersionException()
        : base(DefaultMessage)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="CudaUnsupportedPtxVersionException"/> class.
    /// </summary>
    /// <remarks>
    /// This indicates that the provided PTX was compiled with an unsupported toolchain. The most common reason for this, is the PTX was generated by a compiler newer than what is supported by the CUDA driver and PTX JIT compiler.
    /// </remarks>
    /// <param name="innerException">The inner exception.</param>
    public CudaUnsupportedPtxVersionException(Exception innerException)
        : base(DefaultMessage, innerException)
    {
    }
}
