trigger:
  - master

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  GitVersion.SemVer: ''
  GitVersion.NuGetVersionV2: ''

extends:
  template: pipeline.yml
  parameters:
    configuration: '$(variables.buildConfiguration)'
    ci: false
    deploy-dev: true
    deploy-rc: false
    deploy-prod: false
