find_package(CUDAToolkit)

enable_language(CUDA)

file(GLOB_RECURSE SRC_FILES CONFIGURE_DEPENDS
        ${CMAKE_CURRENT_LIST_DIR}/src/*.cu)

file(GLOB_RECURSE HEADER_FILES CONFIGURE_DEPENDS
        ${CMAKE_CURRENT_LIST_DIR}/src/*.cuh)

set(CUDA_SRC_FILES ${SRC_FILES} PARENT_SCOPE)
set(CUDA_HEADER_FILES ${SRC_FILES} PARENT_SCOPE)