# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - '*' 
      - '**/*'
  pull_request:
    branches:
      - '*'
      - '**/*'

jobs:
  Build:
    runs-on: windows-latest-l
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
    - name: Build
      shell: pwsh
      run: |
        .\eng\build.ps1 -C Release -CleanBuild 1 -PackageVersion ${{ env.GitVersion_FullSemVer }}
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./artifacts/bin/release/*.nupkg --skip-duplicate --no-symbols true -k ${{ secrets.NUGET_API_KEY }}
